# Generated by Django 6.0.2 on 2026-02-08 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_monthly_electricity_bill_kwh', models.FloatField(default=1000.0, help_text='Total office electricity usage in kWh')),
                ('grid_intensity', models.FloatField(default=0.82, help_text='kg CO2 per kWh (India Default: 0.82)')),
                ('total_cloud_usage_kwh', models.FloatField(default=500.0, help_text='Total cloud infrastructure usage in kWh')),
                ('server_count', models.IntegerField(default=10, help_text='Number of physical on-premise servers')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('home_address', models.CharField(default='Home', max_length=255)),
                ('home_commute_distance_km', models.FloatField(default=10.0, help_text='One-way distance from Home to Office')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('hours_worked', models.FloatField(default=8.0)),
                ('is_home_commute', models.BooleanField(default=True, verbose_name='Commuting from Home?')),
                ('start_location', models.CharField(blank=True, help_text='If not home, where from?', max_length=255, null=True)),
                ('commute_mode', models.CharField(choices=[('EV', 'Electric Vehicle (0.01 kg/km)'), ('CAR', 'Car (0.18 kg/km)'), ('AUTO', 'Auto Rickshaw (0.08 kg/km)'), ('BIKE', 'Motorbike (0.04 kg/km)'), ('METRO', 'Metro (0.02 kg/km)'), ('BUS', 'Bus (0.05 kg/km)'), ('WFH', 'Work From Home (0.00 kg/km)')], default='METRO', max_length=10)),
                ('commute_distance_km', models.FloatField(default=0.0, help_text='One-way distance')),
                ('vcpu_hours', models.FloatField(default=0.0, help_text='vCPU hours used today')),
                ('storage_gb', models.FloatField(default=0.0, help_text='GB of storage used today')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='carbon_app.employee')),
            ],
        ),
    ]
